### ISSUE TITLE
Website - Media

### ISSUE THREAD

**Issue by pramslam** [pramslam/IndieGameCon#27]
- [x] Articles
- [x] Blog Posts
- [x] Media Links

**Comment by andy-dandy** [comment]
Make this page but leave it blank for now because the blog posts, articles, etc will come later after we have sponsors and workshops so we can actually hype it up accurately. So just have a "coming soon!" type thing for now

David has a personal website he will write a blog post on, which will be linked to on this page

Articles: contact local newspapers, get interviews

Media links: Promo videos, if there's music artists link to their pages

**Comment by pramslam** [comment]
Please put this video up on the media page:

Indie Game Con 2016:
https://www.youtube.com/watch?v=cOagQX87SCI

**Comment by pramslam** [comment]
This page is essentially done. We just need to add content as it comes.
